### ISSUE TITLE
Cant get the app.js to work with facebook

### ISSUE THREAD

**Issue by sanjib75** [ciaranj/connect-auth#15]
I could get the facebook, yahoo and twitter auth stuff working but cant seem to get facebook working.

I get the following error

TypeError: Object [object Object] has no method 'getAuthorizeUrl'
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/connect-auth/0.1.3/package/lib/auth.strategies/facebook.js:59:35)
    at next (/usr/local/lib/node/.npm/connect-auth/0.1.3/package/lib/strategyExecutor.js:49:37)
    at [object Object].authenticate (/usr/local/lib/node/.npm/connect-auth/0.1.3/package/lib/strategyExecutor.js:55:10)
    at IncomingMessage.authenticate (/usr/local/lib/node/.npm/connect-auth/0.1.3/package/lib/auth.js:91:31)
    at Object.<anonymous> (/home/sanjib/raptive/trunk/raptive/tests/unit/app.js:50:9)
    at pass (/home/poushali/.node_libraries/connect/middleware/router.js:65:27)
    at Object.router [as handle](/home/poushali/.node_libraries/connect/middleware/router.js:80:10)
    at next (/home/poushali/.node_libraries/connect/index.js:241:23)
    at next (/home/poushali/.node_libraries/connect/index.js:188:17)
    at pass (/home/poushali/.node_libraries/connect/middleware/router.js:78:17)

Did any of you find the same issue with facebook?

**Comment by ciaranj** [comment]
Hmmm I've no idea, that object (OAuth2) should _definitely_ have that method, is this still an issue for you ?

**Comment by diversario** [comment]
Facebook definitely doesn't work. In fact, updated app.js is broken in at least 5 places, including non-existing modules.

facebook.js is calling
var OAuth= require("./oauth/oauth").OAuth2 which I can't find anywhere in oauth.js.

After I fixed errors in app.js, this is what I get:
node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: undefined is not a function
    at CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
    at Function.<anonymous> (/usr/local/lib/node/.npm/connect-auth/0.2.1/package/lib/auth.strategies/facebook.js:16:14)
    at Object.<anonymous> (/home/ilya/node/app.js:256:34)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at Array.<anonymous> (module.js:402:10)

##     at EventEmitter._tickCallback (node.js:108:26)

Is this module maintained at all anymore? Just want to know so that if it's not - I could go ahead and look for something else.

**Comment by ciaranj** [comment]
Reasonably regularly, yes.  Facebook was working very recently. Not tested against the newest version of connect though.  Oauth2 does exist in node-oauth, I wrote it.

**Comment by diversario** [comment]
Weird. Could you run app.js and see if it works for you? This one - https://github.com/ciaranj/connect-auth/blob/master/examples/app.js

**Comment by ciaranj** [comment]
Afraid not, on my iPhone.  if you're going straight from git make sure you've updated the submodules.  If npm, make sure you've updated node-oauth, also presumably this is on node.js > 0.4

**Comment by diversario** [comment]
npm 404's for node-oauth :(
I installed express, connect-auth and connect from nmp, not git. Are npm versions different?

**Comment by ciaranj** [comment]
Re-checked working in 0.3.0

**Comment by guiomie** [comment]
I am using version 3.0, and I am also getting an error similar:

Error: Cannot find module 'oauth'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object. (/mnt/ws/users/guiomie/62592/node_modules/connect-auth/lib/auth.strategies/facebook.js:5:12)

Part of the code it points at (5:12:

var OAuth= require("oauth").OAuth2,
    url = require("url"),
    connect = require("connect"),
    http = require('http');

Facebook= module.exports= function(options, server) {
  options= options || {}
  var that= {};

I used npm, running on cloud9 ide.

**Comment by ciaranj** [comment]
did you install oauth (npm install oauth) ?

**Comment by guiomie** [comment]
No I hadn't. I thought the required packages were included with connect-auth. It compiles fine now. Feel free to delete my messages if they dont suit the purpose of this issue. Thank you.

**Comment by ciaranj** [comment]
connect-auth only includes the minimum requirements, the OAuth consumer derived authentication strategies are optional, ... but this approach does confuse the hell out of everyone ;)
